baseURL = 'https://matutosi.github.io/'
languageCode = 'jp-jp'
title = 'matutosi'
publishDir = "docs"
  # theme = "github-style"
  # theme = "mainroad"
  # theme = "techdoc"
theme = "learn"

[Params]
  highlightColor = "#008000" # Override highlight color

[Params.sidebar]
  home   = "right"
  list   = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist", "social"]

[[Menus.main]]
  Name = "Home"
  URL = "/"
  weight = 1

[[Menus.main]]
  Name = "Categories"
  URL = "/categories/"
  weight = 2

[[Menus.main]]
  Name = "Tags"
  URL = "/tags/"
  weight = 3
