baseURL = 'https://matutosi.github.io/'
languageCode = 'jp-jp'
title = 'matutosi'
publishDir = "docs"
  theme = "mainroad"
  # theme = "techdoc"
  # theme = "github-style"
  # theme = "learn"

  # [outputs]
  #   home = [ "HTML"]

[Params]
  #   themeVariant = "gold"
  highlightColor = "#008000" # Override highlight color
  post_meta = ["date", "categories"] # Order of post meta information

[Params.sidebar]
  home   = "right"
  list   = "right"
  single = "right"
  widgets = ["recent", "categories", "taglist"]
  #   widgets = ["search", "recent", "categories", "taglist", "social"]

[[Menus.main]]
  Name = "Home"
  URL = "/"
  weight = 1

[[Menus.main]]
  Name = "Categories"
  URL = "/categories/"
  weight = 2

[[Menus.main]]
  Name = "Tags"
  URL = "/tags/"
  weight = 3
